#!/bin/sh

f1() {	# default setting
	sysctl kern.timecounter.hardware=PIIX
	return
	ifconfig ed2 delete
	dhclient ed2
	sysctl net.inet.ip.fw.verbose=1
}

# test tables
f2() {
	ipfw table 2 add 22 2000
	ipfw table 2 add 53 3000
	ipfw table 2 add 80 4000
	ipfw table 2 add 127.0.0.1 5000
	ipfw table 2 list
}

f3() {
	ipfw -q flush
	ipfw add 100 count log out
	ipfw add 200 skipto tablearg lookup dst-port 2
	ipfw add 300 skipto tablearg lookup dst-ip 2
	ipfw add 1000 allow ip from any to any
	ipfw add 2000 allow ip from any to any
	ipfw add 3000 allow ip from any to any
	ipfw add 4000 allow ip from any to any
	ipfw add 5000 allow ip from any to any
}

f4() {
	ipfw -q flush
	echo > /etc/libalias.conf
	sysctl net.inet.ip.fw.verbose=1
	ipfw add 100 divert natd log ip from any to any
	ipfw add 100 count ip from any to any
	ipfw add 200 count ip from any to any
	natd -v -interface ed2 &
}

f5() {
	ipfw pipe 10 config bw 80kbit/s
	ipfw add 100 pipe 10 ip from any to any
	ipfw pipe show
}

# test queues
f6() {
	ipfw pipe 1 config bw 400kbit/s queue 30
	#ipfw pipe 2 config bw 180kbit/s
	#ipfw pipe 3 config delay 30ms queue 100kbytes
	ipfw queue 11 config sched 1 weight 1
	ipfw queue 12 config sched 1 weight 2
	ipfw queue 14 config sched 1 weight 4
	ipfw queue 18 config sched 1 weight 8
	ipfw -q flush
	ipfw add 100 queue 11 src-ip 0&3 // low bits 00
	ipfw add 100 queue 12 src-ip 1&3 // low bits 01
	ipfw add 100 queue 14 src-ip 2&3 // low bits 10
	ipfw add 100 queue 18 src-ip 3&3 // low bits 11
}

# jail test
f7() {
jail -c -nXX vnet path=/ host.hostname=test.me  persist=true command=/bin/sh
}

f8() {
	ipfw add 100 queue tablearg lookup dscp 1
	ipfw queue 10 config sched 5 mask queue
	ipfw queue 20 config sched 5 mask queue
	ipfw queue 30 config sched 5 mask queue
	ipfw pipe 5 config bw 80Kbit/s
	# ipfw table 1 add 0 10
	ipfw table 1 add 1 20
	ipfw table 1 add 2 30
	ipfw table 1 list
}

case $1 in
   f[0-9]*)	$*	 ;;
esac
