#!/bin/sh
#
# test the nesting of calls in C
LIM=100
build1() { # build one entry,
	local i=0 j
	local dst=nest_f1.c
	rm -f $dst
	while [ $i -lt $LIM ] ; do
		j=$(( $i + 1 ))
		echo "int f_$j(int x) { x = f_$i(x + 2); return x + 3; }" >> $dst
		i=$j
	done
}

build100() { # build many entries
	rm -rf test100
	mkdir test100
	local i=0 j
	while [ $i -lt $LIM ] ; do
		j=$(( $i + 1 ))
		echo "int f_$i(int); int f_$j(int x) { x = f_$i(x + 2); return x + 3; }" > test100/f$j.c
		i=$j
	done
}
build1
build100
