#!/bin/sh

if [ -f version ]; then
	VN=$(cat version)
else
	VN=$(git describe --tags)
fi

cat >netmap_version.h.tmp <<EOF
#ifndef NETMAP_VERSION
#define NETMAP_VERSION "$VN"
#endif
EOF
[ -e netmap_version.h ] &&
	cmp netmap_version.h.tmp netmap_version.h >/dev/null &&
	exit 0
echo "===> new version: $VN"
mv netmap_version.h.tmp netmap_version.h
