#!/bin/sh

f1() {
	sysctl kern.timecounter.hardware=i8254
	ifconfig ed2 delete
	dhclient ed2
	sysctl net.inet.ip.fw.verbose=1
}

f2() {
	ipfw table 2 add 22 2000
	ipfw table 2 add 53 3000
	ipfw table 2 add 80 4000
	ipfw table 2 add 127.0.0.1 5000
	ipfw table 2 list
}

f3() {
	ipfw -q flush
	ipfw add 100 count log out
	ipfw add 200 skipto tablearg lookup dst-port 2
	ipfw add 300 skipto tablearg lookup dst-ip 2
	ipfw add 1000 allow ip from any to any
	ipfw add 2000 allow ip from any to any
	ipfw add 3000 allow ip from any to any
	ipfw add 4000 allow ip from any to any
	ipfw add 5000 allow ip from any to any
}

f4() {
	ipfw -q flush
	echo > /etc/libalias.conf
	sysctl net.inet.ip.fw.verbose=1
	ipfw add 100 divert natd log ip from any to any
	ipfw add 100 count ip from any to any
	ipfw add 200 count ip from any to any
	natd -v -interface ed2 &
}

case $1 in
   f[0-9]*)	$*	 ;;
esac
