#!/usr/bin/env bash
# restarting fd_server
./functional -c
./functional -o
echo "Server restarted"

# preopening interface that will be needed
./functional -i vale0:v0
./functional -i vale0:v1
./functional -i vale0:v2
echo "Interfaces preopened"

# echo "First send, every port should receive the frame."
./functional -i vale0:v0 -r 100:c -T 1 -s 10:10:10:10:10:10 &>/dev/null &
p1=$!
./functional -i vale0:v1 -r 100:c -T 1 -s 10:10:10:10:10:10 &>/dev/null &
p2=$!
./functional -i vale0:v2 -t 100:c -s 10:10:10:10:10:10 &>/dev/null
e3=$?

wait $p1
e1=$?
wait $p2
e2=$?
echo "Exit value 1: $e1"
echo "Exit value 2: $e2"
echo "Exit value 3: $e3"

# echo "Second send, only v2 should receive the frame."
./functional -i vale0:v2 -r 100:c -T 1 -d 10:10:10:10:10:10 &>/dev/null &
p4=$!
./functional -i vale0:v1 -r 100:c -T 1 -d 10:10:10:10:10:10 -n &>/dev/null &
p5=$!
./functional -i vale0:v0 -t 100:c -d 10:10:10:10:10:10 &>/dev/null
e6=$?

wait $p4
e4=$?
wait $p5
e5=$?
echo "Exit value 4: $e4"
echo "Exit value 5: $e5"
echo "Exit value 6: $e6"
echo "=============================================="
result=$(($e1 + $e2 + $e3 + $e4 + $e5 + $e6))
if [ $result = 0 ] ; then
	echo "Test successful"
	exit 0
else
	echo "Test failed"
	exit 1
fi