#!/usr/bin/env bash
################################################################################
# Test objective: check that a persistent VALE port can't be attached 2 times
#                 to the same VALE bridge, but can be attached to 2 different
#                 bridges.
################################################################################
source test_lib

redirect_std

bridge="vale0"
bridgeA="${bridge}A"
bridgeB="${bridge}B"
port="v0"

create_vale_persistent_port "$port" 0
attach_to_vale_bridge "$bridgeA" "$port" 0
attach_to_vale_bridge "$bridgeA" "$port" 1
attach_to_vale_bridge "$bridgeB" "$port" 0

test_successful "persistent_vale_port_double_attach"