#!/usr/bin/env bash
################################################################################
# Test objective: check if receive copy monitors receives frames when its
#                 monitored VALE port is receiving.
# Operations:
# 0) restart fd_server to have a clean starting state
# 1) create a persistent VALE port (v0).
# 2) connect v0 and a VALE ephimeral port (v1) to the same VALE switch.
# 3) open a receiving copy monitor for v0/r.
# 4) send from v1, check that both v0 and v0/r receive the frame.
################################################################################
source test_lib

restart_fd_server

create_vale_persistent_port "v0" "vale0"
# Pre-opening interface that will be needed. This is needed to avoid a race
# condition between the sending and receiving ports.
./functional -i vale0:v0    &>/dev/null
check_exit $? "pre-open vale0:v0"
# Receiving copy monitor for vale0:v0
./functional -i netmap:v0/r &>/dev/null
check_exit $? "pre-open netmap:v0/r"
./functional -i vale0:v1    &>/dev/null
check_exit $? "pre-open vale0:v1"

./functional -i netmap:v0/r -r 150:d &>/dev/null &
p1=$!
./functional -i vale0:v0    -r 150:d &>/dev/null &
p2=$!
./functional -i vale0:v1    -t 150:d &>/dev/null
e3=$?
wait $p1
e1=$?
wait $p2
e2=$?
check_exit $e1 "receive netmap:v0/r"
check_exit $e2 "receive vale0:v0"
check_exit $e3 "send vale0:v1"

echo "Test successful."