#!/usr/bin/env bash
################################################################################
# Test objective: check if we can send and receive through veth interfaces.
# Operations:
# 0) restart fd_server to have a clean starting state
# 1) create a pair of veth interfaces (veth1A, veth1B).
# 2) send from veth1A and check if veth1B receives it.
################################################################################
source test_lib

restart_fd_server

create_veth_interfaces "veth1"
# Pre-opening interface that will be needed. This is needed to avoid a race
# condition between the sending and receiving ports.
./functional -i netmap:veth1A &>/dev/null
check_exit $? "pre-open netmap:veth1A"
./functional -i netmap:veth1B &>/dev/null
check_exit $? "pre-open netmap:veth1B"

# During the first send we don't receive with the monitor, vale0:v1 should not
# receive the frame.
./functional -i netmap:veth1A -r 150:d &>/dev/null &
p1=$!
./functional -i netmap:veth1B -t 150:d &>/dev/null
e2=$?
wait $p1
e1=$?
check_exit $e1 "receive netmap:veth1A"
check_exit $e2 "send netmap:veth1B"

echo "Test successful."