#!/usr/bin/env bash
################################################################################
# Test objective: check that a persistent VALE port can't be attached 2 times
#                 to the same VALE bridge, but can be attached to 2 different
#                 bridges.
################################################################################
source test_lib

parse_send_recv_arguments "$@"
verbosity="${verbosity:-}"

bridge="vale0"
bridgeA="${bridge}A"
bridgeB="${bridge}B"
port="v0"

restart_fd_server

create_vale_persistent_port "$port" 0
attach_to_vale_bridge "$bridgeA" "$port" 0
attach_to_vale_bridge "$bridgeA" "$port" 1
attach_to_vale_bridge "$bridgeB" "$port" 0

test_successful "$0"