#!/bin/bash -eu

sudo modprobe netmap

# Run control API tests
pushd .
cd utils
make
sudo ./ctrl-api-test
popd

sudo rmmod netmap

# Run integration tests
sudo modprobe netmap
pushd .
cd utils
sudo ./randomized_tests
popd
sudo rmmod netmap
