CFLAGS += -Wall -O2 -g
CFLAGS += -I.

PROG = tree_test
OBJS = bplus_impl.o bplus_support.o

all: $(PROG)
tree_test: tree_test.c $(OBJS)
	$(CC) $(CFLAGS) -o tree_test tree_test.c $(OBJS)
bplus_impl.o: bplus_impl.c
	$(CC) $(CFLAGS) -c bplus_impl.c
bplus_support.o: bplus_support.c
	$(CC) $(CFLAGS) -c bplus_support.c
clean:
	-@rm -f $(PROG) $(OBJS)
