#!/bin/sh

f1() {
	sysctl kern.timecounter.hardware=i8254
	ifconfig ed2 delete
	dhclient ed2
	sysctl net.inet.ip.fw.verbose=1
}

init() {
	local a=$1
	[ "x$a" = "x" ] && a=10.0.0.2
	echo "prepare for tests with netsend"
	ifconfig ix0 $1
	sysctl dev.ix.0.enable_aim=0
	sysctl dev.ix.0.queue0.interrupt_rate=5000
	sysctl dev.ix.0.fc=0
	sysctl dev.cpu.0.freq=2934
	sysctl dev.netmap.drop
	sysctl net.inet.icmp.icmplim=0
	echo netsend 10.0.0.1 5555 18 0 5
}

run_test() { # port num len breakpoint
	local i ports=$1
	shift
	echo "### break $3 cores $1 len $2"
	sysctl dev.netmap.drop=$3
	for i in $1; do (netsend 10.0.0.1 $ports $2 0 5 &) ; done
}

batch() { # ports len breakpoint
	local i ports=$1 len=$2 bp=$3
	for i in 1 2 3 4; do
	    run_test $ports 0 $len $bp 2>&1 | grep -E "###|time/|send rate"
	done
	for i in 1 2 3 4; do
	    run_test $ports "0 1 2 3" $len $bp 2>&1 | grep -E "###|time/|send rate"
	done
}

go() { # ports len breakpoints
	local i ports=$1 len=$2
	shift; shift
	for i in $* ; do
		batch $ports $len $i
	done
}

case $1 in
   *)	$*	 ;;
esac
